#!/usr/bin/env bash
#
# Layer 0: install the GUI launcher + Python package into /opt/autonav/.
#
# Why this layer exists: the kiosk session created in Layer 1 runs
# as the `autonav-kiosk` user, which has no group membership on the
# admin user's $HOME. Without a system-readable copy of the launcher
# and the autonav_gui_hud package, the Openbox autostart's
# `exec /opt/autonav/run-gui.sh` cannot find either of them.
#
# Idempotent. Re-run after pulling new GUI code to refresh
# /opt/autonav/autonav_gui_hud/.
#
# Run on the Jetson as a normal admin user. Uses sudo for /opt writes.

set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"
GUI_PKG_SRC="$REPO_ROOT/isaac_ros-dev/src/autonav-gui-hud/autonav_gui_hud"
XSAVER_SRC="$REPO_ROOT/scripts/kiosk/config/xscreensaver"
DEST="/opt/autonav"

echo "=== Layer 0: install GUI to $DEST ==="
echo "repo root  : $REPO_ROOT"
echo "package src: $GUI_PKG_SRC"
echo "dest       : $DEST"
echo

if [ ! -d "$GUI_PKG_SRC" ]; then
    echo "ERROR: $GUI_PKG_SRC not found. Run this script from inside the AutoNav repo." >&2
    exit 1
fi
if [ ! -r "$XSAVER_SRC" ]; then
    echo "ERROR: $XSAVER_SRC missing. Expected the kiosk xscreensaver template." >&2
    exit 1
fi

echo "[1/3] Creating $DEST tree"
sudo install -d -m 0755 "$DEST"
sudo install -d -m 0755 "$DEST/autonav_gui_hud"
sudo install -d -m 0755 "$DEST/config"

echo "[2/3] Copying autonav_gui_hud Python package"
# rsync with --delete so stale modules from a previous install get
# removed; --exclude __pycache__/*.pyc so we don't ship admin-built
# bytecode the kiosk user can't write to (would cause silent
# regeneration races on every launch).
if command -v rsync >/dev/null 2>&1; then
    sudo rsync -a --delete \
        --exclude='__pycache__' --exclude='*.pyc' \
        "$GUI_PKG_SRC/" "$DEST/autonav_gui_hud/"
else
    # Fallback for minimal images without rsync. cp -aT plus a manual
    # __pycache__ purge produces the same result.
    sudo rm -rf "$DEST/autonav_gui_hud"
    sudo cp -aT "$GUI_PKG_SRC" "$DEST/autonav_gui_hud"
    sudo find "$DEST/autonav_gui_hud" -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true
    sudo find "$DEST/autonav_gui_hud" -name '*.pyc' -delete 2>/dev/null || true
fi
sudo chmod -R a+rX "$DEST/autonav_gui_hud"

echo "[3/3] Installing /opt/autonav/run-gui.sh and config/xscreensaver"
sudo install -m 0644 "$XSAVER_SRC" "$DEST/config/xscreensaver"

# Heredoc-generated launcher. Lives flat under /opt/autonav/ rather
# than chasing the in-repo $SCRIPT_DIR/../src layout, so the kiosk
# user only needs read+exec on /opt/autonav/.
sudo tee "$DEST/run-gui.sh" >/dev/null <<'LAUNCHER_EOF'
#!/usr/bin/env bash
# Installed launcher for the AutoNav GUI HUD.
# Generated by scripts/kiosk/install-layer0-gui.sh — edit the
# generator, not this file. Rerun the installer after pulling new
# GUI code to refresh /opt/autonav/autonav_gui_hud/.
#
# Also brings up an xscreensaver daemon so Ctrl+Shift+L (intercepted
# inside the GUI and forwarded to `xscreensaver-command -lock`)
# actually locks the screen even outside the full kiosk session.

DEST=/opt/autonav

# Source ROS2 so rclpy is available for live mode.
if [ -f /opt/ros/humble/setup.bash ]; then
    source /opt/ros/humble/setup.bash
fi

# Match the container's ROS domain.
export ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}

# Force system Qt5 plugins so PyQt5/matplotlib render correctly.
export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/aarch64-linux-gnu/qt5/plugins/platforms
export DISPLAY="${DISPLAY:-:0}"

# Bring up the OS screen locker. pgrep makes this idempotent so a
# re-launch of run-gui.sh doesn't spawn a second daemon.
if command -v xscreensaver >/dev/null 2>&1; then
    # First-run: drop in the kiosk locker config (manual lock only,
    # 5min passwd timeout). User can override by editing ~/.xscreensaver.
    if [ ! -f "$HOME/.xscreensaver" ] && [ -r "$DEST/config/xscreensaver" ]; then
        cp "$DEST/config/xscreensaver" "$HOME/.xscreensaver"
    fi
    if ! pgrep -x xscreensaver >/dev/null 2>&1; then
        xscreensaver -no-splash >/dev/null 2>&1 &
        disown 2>/dev/null || true
    fi
else
    echo "[run-gui] xscreensaver not installed; Ctrl+Shift+L will not lock." >&2
fi

cd "$DEST"
exec python3 -m autonav_gui_hud.hud_node "$@"
LAUNCHER_EOF
sudo chmod 0755 "$DEST/run-gui.sh"

cat <<EOF

Layer 0 install complete. Resulting tree:

  $DEST/
  ├── run-gui.sh                 (0755, callable as any user)
  ├── autonav_gui_hud/           (Python package, world-readable)
  └── config/
      └── xscreensaver           (template for ~/.xscreensaver)

Sanity check:
  ls -l $DEST/run-gui.sh
  sudo -u nobody test -r $DEST/run-gui.sh && echo 'OK: world-readable'

Next: ./install-layer1-kiosk-wm.sh
EOF
